var car = ["BMW", "Mercedes", "Audi", "Ferrari", "Lamborgini"];
console.log("car == 'BMW'? I predict True.");
console.log(car[0] == "BMW");
console.log("car =='Toyota'? I predict false.");
console.log(car[0] == "Toyoto");
console.log("car =='Mercedes'? I predict True.");
console.log(car[1] == "Mercedes");
console.log("car =='Alto'? I predict flase.");
console.log(car[1] == "Alto");
console.log("car =='Audi'? I predict True.");
console.log(car[2] == "Audi");
console.log("car =='vigo'? I predict false?");
console.log(car[2] == "vigo");
console.log("car =='Ferrari'? I predict True.");
console.log(car[3] == "Ferrari");
console.log("car =='Mehran'? I predict false.");
console.log(car[3] == "Mehran");
console.log("car =='Lamborgini'? I predict True.");
console.log(car[4] == "Lamborgini");
console.log("car =='Cultus'? I predict false.");
console.log(car[4] == "Cultus");
